### ISSUE TITLE
how to solve det of a matrix?

### ISSUE THREAD

**Issue by zhangfq-chemistry** [lubgr/tsym#26]

**Comment by lubgr** [comment]
Thanks for your question, @zhangfq-chemistry! Have a look at the README in the toplevel directory of the repo - you can find an example how to compute the determinant of a matrix, and let me know if you have specific questions. Note that this library doesn't ship with its own matrix/vector types, but let's you use anything that has overloaded call or subscript operators (e.g. Eigen matrices, Boost UBLAS, `std::vector<std::vector<tsym::Var>>`  etc.
